# Aggression Baselines

Each aggression score is in the ordered set [-3, -2, -1, 0, 1, 2, 3]. For each revision, we have k scores that we can aggregate to get a label. Depending on how we aggregate, we can get a regression or a multi-class classification problem. We will build baselines for each setting for both the random and the blocked data.

In [22]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from baselines import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
data_filename  = '../../data/v4_annotated/annotated_onion_layer_5_rows_0_to_5000_raters_20.csv'
d_b = pd.read_csv(data_filename)
d_b = d_b.query('_golden == False')
d_b.index = d_b.rev_id
l_b = d_b['aggression_score']

In [10]:
data_filename  = '../../data/v4_annotated/annotated_random_data_rows_0_to_5000_raters_20.csv'
d_r = pd.read_csv(data_filename)
d_r = d_r.query('_golden == False')
d_r.index = d_r.rev_id
l_r = d_r['aggression_score']

In [11]:
k = 20

# Aggregation method  : average labels
# Evaluation metric       : pearson correlation

In [45]:
get_baseline_matrix(l_b, k, average, pearson)

Num comments with k labels 4448

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.522,0.607,0.633,0.670,0.675,0.696,0.695,0.680,0.695,0.699,0.704,0.707,0.704,0.715,0.708,0.709,0.712,0.722,0.718
2,0,0.695,0.729,0.759,0.769,0.790,0.786,0.790,0.803,0.808,0.800,0.806,0.806,0.805,0.811,0.815,0.814,0.823,0
3,0,0,0.780,0.799,0.809,0.829,0.831,0.835,0.837,0.837,0.848,0.849,0.856,0.855,0.852,0.857,0.858,0,0
4,0,0,0,0.819,0.834,0.841,0.846,0.867,0.861,0.871,0.873,0.872,0.873,0.876,0.880,0.885,0,0,0
5,0,0,0,0,0.851,0.863,0.874,0.877,0.879,0.885,0.891,0.890,0.895,0.895,0.897,0,0,0,0
6,0,0,0,0,0,0.876,0.875,0.886,0.890,0.896,0.901,0.906,0.907,0.907,0,0,0,0,0
7,0,0,0,0,0,0,0.887,0.894,0.898,0.902,0.905,0.912,0.912,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.902,0.908,0.907,0.916,0.914,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.913,0.915,0.917,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.921,0,0,0,0,0,0,0,0,0

In [17]:
get_baseline_matrix(l_r, k, average, pearson)

Num comments with k labels 4490

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.264,0.339,0.387,0.396,0.399,0.402,0.444,0.446,0.456,0.461,0.473,0.463,0.456,0.489,0.472,0.462,0.490,0.505,0.469
2,0,0.423,0.460,0.515,0.509,0.544,0.534,0.563,0.587,0.571,0.589,0.589,0.599,0.592,0.601,0.610,0.615,0.622,0
3,0,0,0.506,0.549,0.578,0.577,0.608,0.624,0.631,0.637,0.651,0.635,0.668,0.648,0.664,0.681,0.671,0,0
4,0,0,0,0.583,0.607,0.645,0.661,0.650,0.675,0.664,0.686,0.689,0.693,0.688,0.702,0.712,0,0,0
5,0,0,0,0,0.647,0.666,0.674,0.698,0.708,0.709,0.721,0.724,0.731,0.748,0.738,0,0,0,0
6,0,0,0,0,0,0.685,0.699,0.717,0.724,0.736,0.739,0.747,0.752,0.755,0,0,0,0,0
7,0,0,0,0,0,0,0.721,0.731,0.743,0.748,0.757,0.765,0.770,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.734,0.746,0.762,0.765,0.781,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.768,0.768,0.775,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.790,0,0,0,0,0,0,0,0,0

# Aggregation method  : average labels
# Evaluation metric       : spearman correlation

In [14]:
get_baseline_matrix(l_b, k, average, spearman)

Num comments with k labels 4448

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.546,0.574,0.614,0.630,0.654,0.667,0.658,0.653,0.674,0.671,0.649,0.671,0.669,0.671,0.677,0.673,0.674,0.673,0.677
2,0,0.653,0.681,0.704,0.716,0.721,0.734,0.736,0.742,0.750,0.751,0.755,0.750,0.757,0.764,0.766,0.769,0.770,0
3,0,0,0.717,0.744,0.755,0.762,0.773,0.777,0.784,0.784,0.795,0.801,0.803,0.800,0.804,0.804,0.813,0,0
4,0,0,0,0.765,0.784,0.778,0.791,0.803,0.810,0.815,0.814,0.823,0.825,0.830,0.834,0.836,0,0,0
5,0,0,0,0,0.799,0.805,0.821,0.822,0.831,0.828,0.842,0.844,0.836,0.850,0.846,0,0,0,0
6,0,0,0,0,0,0.823,0.824,0.832,0.840,0.839,0.853,0.856,0.856,0.863,0,0,0,0,0
7,0,0,0,0,0,0,0.838,0.844,0.856,0.854,0.859,0.864,0.870,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.848,0.859,0.864,0.867,0.869,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.864,0.872,0.875,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.877,0,0,0,0,0,0,0,0,0

In [15]:
get_baseline_matrix(l_r, k, average, spearman)

Num comments with k labels 4490

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.255,0.287,0.332,0.329,0.343,0.365,0.376,0.395,0.389,0.415,0.403,0.395,0.400,0.409,0.405,0.412,0.415,0.395,0.435
2,0,0.372,0.396,0.421,0.421,0.442,0.445,0.464,0.473,0.481,0.475,0.490,0.499,0.502,0.490,0.482,0.519,0.519,0
3,0,0,0.429,0.466,0.474,0.469,0.525,0.518,0.525,0.529,0.525,0.536,0.538,0.547,0.555,0.557,0.544,0,0
4,0,0,0,0.496,0.487,0.504,0.525,0.544,0.552,0.543,0.564,0.580,0.575,0.580,0.591,0.578,0,0,0
5,0,0,0,0,0.532,0.545,0.553,0.568,0.575,0.592,0.587,0.596,0.601,0.595,0.621,0,0,0,0
6,0,0,0,0,0,0.569,0.587,0.586,0.599,0.601,0.614,0.620,0.621,0.636,0,0,0,0,0
7,0,0,0,0,0,0,0.588,0.601,0.617,0.619,0.618,0.635,0.658,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.622,0.629,0.636,0.650,0.646,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.643,0.647,0.656,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.665,0,0,0,0,0,0,0,0,0

# Aggregation method  : average
# Evaluation metric   : RMSE

In [20]:
get_baseline_matrix(l_b, k, average, rmse)

Num comments with k labels 4448

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,1.166,0.975,0.918,0.871,0.870,0.871,0.870,0.851,0.832,0.862,0.837,0.828,0.843,0.814,0.828,0.808,0.839,0.832,0.814
2,0,0.798,0.733,0.688,0.674,0.648,0.640,0.629,0.612,0.622,0.618,0.610,0.620,0.613,0.608,0.607,0.600,0.601,0
3,0,0,0.661,0.613,0.581,0.558,0.551,0.542,0.538,0.531,0.523,0.517,0.518,0.513,0.509,0.502,0.498,0,0
4,0,0,0,0.562,0.543,0.524,0.494,0.495,0.487,0.474,0.464,0.459,0.451,0.453,0.457,0.440,0,0,0
5,0,0,0,0,0.498,0.484,0.473,0.460,0.447,0.431,0.436,0.422,0.427,0.416,0.408,0,0,0,0
6,0,0,0,0,0,0.456,0.449,0.433,0.420,0.419,0.408,0.410,0.389,0.392,0,0,0,0,0
7,0,0,0,0,0,0,0.426,0.419,0.402,0.398,0.393,0.374,0.380,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.396,0.390,0.379,0.369,0.358,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.379,0.364,0.358,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.355,0,0,0,0,0,0,0,0,0

In [21]:
get_baseline_matrix(l_r, k, average, rmse)

Num comments with k labels 4490

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.945,0.840,0.748,0.753,0.734,0.730,0.720,0.697,0.707,0.706,0.717,0.712,0.688,0.705,0.684,0.689,0.690,0.679,0.686
2,0,0.661,0.607,0.589,0.560,0.530,0.532,0.517,0.507,0.525,0.507,0.504,0.504,0.490,0.488,0.495,0.510,0.498,0
3,0,0,0.550,0.514,0.484,0.467,0.457,0.450,0.445,0.430,0.423,0.428,0.440,0.426,0.418,0.417,0.414,0,0
4,0,0,0,0.460,0.448,0.425,0.418,0.406,0.397,0.399,0.388,0.385,0.380,0.373,0.381,0.387,0,0,0
5,0,0,0,0,0.428,0.409,0.386,0.383,0.370,0.358,0.354,0.353,0.341,0.343,0.344,0,0,0,0
6,0,0,0,0,0,0.379,0.375,0.362,0.351,0.339,0.344,0.336,0.326,0.328,0,0,0,0,0
7,0,0,0,0,0,0,0.353,0.341,0.335,0.325,0.322,0.322,0.306,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.333,0.312,0.311,0.307,0.307,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.314,0.301,0.298,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.301,0,0,0,0,0,0,0,0,0

# Aggregation method  : average
# Evaluation metric   : R^2

In [23]:
get_baseline_matrix(l_b, k, average, r2_score)

Num comments with k labels 4448

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.071,0.304,0.357,0.456,0.449,0.445,0.467,0.490,0.505,0.488,0.504,0.492,0.499,0.504,0.518,0.517,0.511,0.486,0.529
2,0,0.404,0.475,0.557,0.578,0.618,0.614,0.617,0.623,0.642,0.642,0.638,0.652,0.663,0.652,0.673,0.663,0.657,0
3,0,0,0.535,0.617,0.634,0.655,0.685,0.691,0.708,0.695,0.715,0.723,0.712,0.713,0.731,0.720,0.742,0,0
4,0,0,0,0.631,0.676,0.700,0.728,0.745,0.733,0.748,0.746,0.772,0.768,0.760,0.772,0.772,0,0,0
5,0,0,0,0,0.714,0.724,0.733,0.748,0.775,0.776,0.782,0.790,0.790,0.796,0.802,0,0,0,0
6,0,0,0,0,0,0.743,0.757,0.782,0.787,0.798,0.806,0.814,0.818,0.812,0,0,0,0,0
7,0,0,0,0,0,0,0.780,0.790,0.803,0.803,0.817,0.824,0.829,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.794,0.811,0.823,0.833,0.835,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.821,0.829,0.835,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.836,0,0,0,0,0,0,0,0,0

In [24]:
get_baseline_matrix(l_r, k, average, r2_score)

Num comments with k labels 4490

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,-0.477,-0.106,-0.007,0.076,0.124,0.146,0.162,0.173,0.151,0.190,0.186,0.224,0.198,0.183,0.226,0.236,0.211,0.233,0.197
2,0,-0.211,0.023,0.144,0.220,0.270,0.255,0.276,0.268,0.289,0.329,0.283,0.347,0.357,0.369,0.354,0.350,0.339,0
3,0,0,0.036,0.194,0.263,0.262,0.308,0.340,0.337,0.368,0.388,0.404,0.425,0.423,0.417,0.410,0.458,0,0
4,0,0,0,0.196,0.275,0.309,0.347,0.398,0.442,0.423,0.474,0.450,0.441,0.463,0.486,0.487,0,0,0
5,0,0,0,0,0.279,0.352,0.397,0.414,0.475,0.463,0.488,0.492,0.521,0.514,0.526,0,0,0,0
6,0,0,0,0,0,0.385,0.422,0.441,0.474,0.508,0.504,0.522,0.541,0.543,0,0,0,0,0
7,0,0,0,0,0,0,0.459,0.461,0.512,0.525,0.528,0.570,0.557,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.493,0.504,0.537,0.544,0.548,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.514,0.566,0.564,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.566,0,0,0,0,0,0,0,0,0

# Aggregation method  : most common label (plurality) 
# Evaluation metric       : accuracy

In [46]:
#get_baseline_matrix(l_b, k, plurality, accuracy_score)

In [47]:
#get_baseline_matrix(l_r, k, plurality, accuracy_score)

# WARNING:  Volatile Functions

# Aggregation method : empirical distribution
# Evaluation metric : cross entropy

In [48]:
#get_baseline_matrix(l_b, k, empirical_dist, cross_entropy)

In [49]:
#get_baseline_matrix(l_r, k, empirical_dist, cross_entropy)

# Aggregation method : empirical distribution
# Evaluation metric : KL Divergence

In [50]:
#get_baseline_matrix(l_b, k, empirical_dist, kl_divergence)

In [51]:
#get_baseline_matrix(l_r, k, empirical_dist, kl_divergence)