# Personal Attack Baselines

Each personal attack annotation is in the set ['not_attack', 'other', 'quoting', 'recipient', 'third_party']. For each revision, we have k annotations that we can aggregate to get a label. We can treat this problem as a single multi-class problem or a several binary classification problems.

In [52]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from baselines import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [53]:
data_filename  = '../data/v4_annotated/annotated_onion_layer_5_rows_0_to_5000_raters_20.csv'
d = pd.read_csv(data_filename)
d = d.query('_golden == False')
d.index = d.rev_id
d = tidy_labels(d)

In [54]:
l_recip = d['recipient']
l_attack = d['attack']

In [55]:
k = 20

# Aggregation method  : pred: average labels gold: plurality
# Evaluation metric       : auc

In [50]:
get_baseline_matrix(l_recip, k, average, roc_auc)

Num comments with k labels 4582

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.707,0.779,0.762,0.798,0.777,0.796,0.778,0.801,0.789,0.802,0.795,0.809,0.793,0.808,0.805,0.798,0.803,0.796,0.795
2,0,0.846,0.843,0.876,0.856,0.877,0.867,0.875,0.873,0.886,0.891,0.893,0.877,0.887,0.876,0.894,0.879,0.900,0
3,0,0,0.878,0.909,0.900,0.910,0.906,0.912,0.918,0.918,0.914,0.925,0.919,0.927,0.921,0.921,0.922,0,0
4,0,0,0,0.918,0.921,0.929,0.921,0.934,0.934,0.944,0.939,0.947,0.932,0.940,0.946,0.945,0,0,0
5,0,0,0,0,0.926,0.935,0.935,0.945,0.941,0.951,0.944,0.949,0.952,0.957,0.953,0,0,0,0
6,0,0,0,0,0,0.955,0.953,0.956,0.954,0.957,0.956,0.954,0.963,0.965,0,0,0,0,0
7,0,0,0,0,0,0,0.952,0.960,0.957,0.961,0.963,0.966,0.962,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.965,0.963,0.962,0.965,0.968,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.968,0.971,0.967,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.973,0,0,0,0,0,0,0,0,0

In [51]:
get_baseline_matrix(l_attack, k, average, roc_auc)

Num comments with k labels 4582

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,0.712,0.752,0.758,0.790,0.774,0.792,0.782,0.801,0.785,0.799,0.789,0.812,0.791,0.797,0.793,0.808,0.796,0.808,0.805
2,0,0.838,0.828,0.879,0.849,0.871,0.864,0.875,0.869,0.875,0.875,0.880,0.880,0.882,0.882,0.886,0.885,0.875,0
3,0,0,0.865,0.896,0.889,0.901,0.903,0.910,0.901,0.909,0.913,0.915,0.909,0.918,0.915,0.918,0.917,0,0
4,0,0,0,0.912,0.898,0.922,0.912,0.925,0.924,0.930,0.928,0.934,0.933,0.936,0.929,0.936,0,0,0
5,0,0,0,0,0.913,0.932,0.932,0.940,0.936,0.938,0.938,0.945,0.945,0.945,0.945,0,0,0,0
6,0,0,0,0,0,0.941,0.938,0.942,0.949,0.950,0.947,0.950,0.953,0.955,0,0,0,0,0
7,0,0,0,0,0,0,0.941,0.953,0.945,0.952,0.954,0.956,0.955,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0.951,0.951,0.963,0.955,0.960,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0.954,0.963,0.960,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0.963,0,0,0,0,0,0,0,0,0

# Aggregation method  : most common label (plurality) 
# Evaluation metric       : accuracy

In [60]:
#get_baseline_matrix(l_recip, 3, plurality, accuracy_score)

In [48]:
#get_baseline_matrix(l_attack, k, plurality, accuracy_score)

# Aggregation method : empirical distribution
# Evaluation metric : cross entropy

In [41]:
#get_baseline_matrix(l_recip, k, empirical_dist, cross_entropy)

In [42]:
#get_baseline_matrix(l_attack, k, empirical_dist, cross_entropy)

# Aggregation method : empirical distribution
# Evaluation metric : KL Divergence

In [43]:
#get_baseline_matrix(l_recip, k, empirical_dist, kl_divergence)

In [44]:
#get_baseline_matrix(l_attack, k, empirical_dist, kl_divergence)